language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
  - CXX=g++-4.8
  - REDIS_SENTINEL_JQ='127.0.0.1:26379'
  - REDIS_SENTINEL_NAME_JQ='jobqueue01'
cache:
  directories:
    - node_modules
node_js:
  - "4.2"
before_script:
  - redis-server /etc/redis/redis.conf --port 6379
  - bash ./deploy/setupSentinel.sh
  - npm prune
install:
  - npm install
script:
  - npm test
branches:
  only:
    - master
    - dev
notifications:
  email: false